version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: $TDP_DB_PASS
      POSTGRES_USER: $TDP_DB_USER
      POSTGRES_DB: $TDP_DB_SCHEMA
    ports:
      - "5432:5432"