version: '3.8'

services:

  database:
    container_name: db_container
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: $TDP_DB_PASS
      POSTGRES_USER: $TDP_DB_USER
      POSTGRES_DB: $TDP_DB_SCHEMA
    ports:
      - ${TDP_DB_PORT}:$TDP_DB_PORT

  backend:
    depends_on:
      - database
    container_name: tdp_backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      TDP_DB_HOST: db_container
      TDP_DB_USER: $TDP_DB_USER
      TDP_DB_PASS: $TDP_DB_PASS
      TDP_DB_SCHEMA: $TDP_DB_SCHEMA
      JWT_SECRET: $JWT_SECRET

  frontend:
    depends_on:
      - backend
    container_name: tdp_frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"