spring:
  application:
    name: the-discipline-program
  datasource:
    url: jdbc:postgresql://${TDP_DB_HOST}:${TDP_DB_PORT}/${TDP_DB_SCHEMA}
    username: ${TDP_DB_USER}
    password: ${TDP_DB_PASS}
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}