spring:
  application:
    name: the-discipline-program
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
  sql:
    init:
      mode: never
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR